[package]
name = "wigame"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/app", "crates/util"]

[dependencies]
app = { path = "./crates/app" }
rayon = "1.5.1"
